name: trading_management
description: "A new Flutter project."
publish_to: 'none'

# 以下では、アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は 1.2.43 のようにドットで区切られた 3 つの数字で構成され、
# 必要に応じて + で区切ったビルド番号を追加できます。
# Flutter のビルド時に、それぞれ --build-name と --build-number を指定すると、
# バージョン番号とビルド番号を上書きできます。
# Android では、build-name は versionName、build-number は versionCode として使用されます。
# Android のバージョニングの詳細:
# https://developer.android.com/studio/publish/versioning
# iOS では、build-name は CFBundleShortVersionString、build-number は CFBundleVersion として使用されます。
# iOS のバージョニングの詳細:
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windows では、build-name は製品およびファイルのバージョンにおけるメジャー、マイナー、パッチ番号として、
# build-number はビルドサフィックスとして使用されます。
version: 1.0.0+1

environment:
  sdk: ^3.12.1

# dependencies では、アプリケーションの動作に必要な他のパッケージを指定します。
# パッケージの依存関係を最新のメジャーバージョンへ自動アップグレードするには、
# `flutter pub upgrade --major-versions` の実行を検討してください。あるいは、
# 以下のバージョン番号を pub.dev で利用可能な最新版へ変更して手動で更新できます。
# 更新可能な依存関係を確認するには、`flutter pub outdated` を実行してください。
dependencies:
  flutter:
    sdk: flutter

  # DB
  drift: ^2.32.0
  drift_flutter: ^0.3.1

  # アイコン
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0

  # 画像のキャッシュ
  cached_network_image: ^3.4.1

  # フラッシュバー
  another_flushbar: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.32.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
