import 'package:trading_management/features/partner/domain/entities/partner.dart';

/// 取引エンティティ
class Trade {
  /// 取引ID
  final String tradeId;

  /// 取引種別ID
  final int tradeTypeId;

  /// 受渡種別ID
  final int deliveryTypeId;

  /// 取引相手
  final Partner partner;

  /// 譲渡するアイテム名
  final String offerItem;

  /// 受け取りたいアイテム名
  final String wantedItem;

  /// 譲渡するアイテムの画像URL
  final String? offerItemImageUrl;

  /// 受け取りたいアイテムの画像URL
  final String? wantedItemImageUrl;

  /// 取引ステージ完了済みコードリスト
  final List<int>? completedStageCodes;

  /// 先払いかどうか
  final bool isPrepaid;

  /// メモ
  final String? memo;

  const Trade({
    required this.tradeId,
    required this.tradeTypeId,
    required this.deliveryTypeId,
    required this.partner,
    required this.offerItem,
    required this.wantedItem,
    required this.offerItemImageUrl,
    required this.wantedItemImageUrl,
    required this.completedStageCodes,
    required this.isPrepaid,
    required this.memo,
  });
}

const dummyTradeList = [
  Trade(
    tradeId: 'test1',
    partner: Partner(
      partnerId: 'partner1',
      userId: 'user_1',
      username: 'ユーザー1',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 1,
    offerItem: 'HAYAYTO',
    wantedItem: '雅功',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: true,
    memo: '交換 / 手渡し 取引成立前',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 1,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: true,
    memo: '交換 / 手渡し 取引成立後',
  ),
  Trade(
    tradeId: 'test3',
    partner: Partner(
      partnerId: 'partner3',
      userId: 'user_3',
      username: 'ユーザー3',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 1,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 7],
    isPrepaid: true,
    memo: '交換 / 手渡し 取引終了後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: true,
    memo: '交換 / 郵送 取引成立前',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: true,
    memo: '交換 / 郵送 取引成立後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 5],
    isPrepaid: true,
    memo: '交換 / 郵送 発送後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 5, 6],
    isPrepaid: true,
    memo: '交換 / 郵送 受取後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 1,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 5, 6, 7],
    isPrepaid: true,
    memo: '交換 / 郵送 取引終了後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 1,
    offerItem: '吉田仁人',
    wantedItem: '¥2,000',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: true,
    memo: null,
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 1,
    offerItem: '吉田仁人',
    wantedItem: '¥2,000',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: true,
    memo: '譲渡 / 手渡し 取引成立後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 1,
    offerItem: '吉田仁人',
    wantedItem: '¥2,000',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 7],
    isPrepaid: true,
    memo: '譲渡 / 手渡し 取引終了後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '¥2,000',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: true,
    memo: '譲渡/郵送 取引成立前',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: true,
    memo: '譲渡/郵送 取引成立後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 3],
    isPrepaid: true,
    memo: '譲渡/郵送 代金受け取り後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 3, 5],
    isPrepaid: true,
    memo: '譲渡/郵送 発送後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 3, 5, 7],
    isPrepaid: true,
    memo: '譲渡/郵送 取引終了後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: false,
    memo: '譲渡/郵送 取引成立後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 5],
    isPrepaid: false,
    memo: '譲渡/郵送 発送後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 3, 5],
    isPrepaid: false,
    memo: '譲渡/郵送 代金受取後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 2,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 3, 5, 7],
    isPrepaid: false,
    memo: '譲渡/郵送 取引終了後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 1,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: true,
    memo: '買取/手渡し 取引成立前',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 1,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: true,
    memo: '買取/手渡し 取引成立後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 1,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 7],
    isPrepaid: true,
    memo: '買取/手渡し 取引終了後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: true,
    memo: '買取/郵送 取引成立前',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: true,
    memo: '買取/郵送 取引成立後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 4],
    isPrepaid: true,
    memo: '買取/郵送 支払い後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 4, 6],
    isPrepaid: true,
    memo: '買取/郵送 受取後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 4, 6, 7],
    isPrepaid: true,
    memo: '買取/郵送 取引終了後',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [],
    isPrepaid: false,
    memo: '買取/郵送 取引成立前 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1],
    isPrepaid: false,
    memo: '買取/郵送 取引成立後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 6],
    isPrepaid: false,
    memo: '買取/郵送 支払い後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 4, 6],
    isPrepaid: false,
    memo: '買取/郵送 受取後 後払い',
  ),
  Trade(
    tradeId: 'test2',
    partner: Partner(
      partnerId: 'partner2',
      userId: 'user_2',
      username: 'ユーザー2',
    ),
    tradeTypeId: 3,
    deliveryTypeId: 2,
    offerItem: '',
    wantedItem: '',
    offerItemImageUrl: null,
    wantedItemImageUrl: null,
    completedStageCodes: [1, 4, 6, 7],
    isPrepaid: false,
    memo: '買取/郵送 取引終了後',
  ),
];
